src:TauProd/Infrared subdirectory.   * Makefile: Created separate link, build, and install targets for each TauProd     source code component.
  src:TauProd/Infrared/Convolve_TauSpc_with_SRF subdirectory.
  * Convolve_TauSpc_with_SRF.f90: Modified to use updated TauProfile modules.
  * Makefile, make.dependencies: Updated source code and dependency list adding
    additional modules due to changes in the Interpolate_Utility module.

  src:TauProd/Infrared/Create_ProcessControl_File subdirectory.
  * Makefile, make.dependencies: Updated source code and dependency list adding
    additional modules due to changes in the Interpolate_Utility module.

  src:TauProd/Infrared/Assemble_TauProfile_Data subdirectory.
  * Assemble_TauProfile_Data.f90: Modified to use updated TauProfile modules.

  src:TauProd/Infrared/LBLRTM/src subdirectory.
  * make.macros: Added MOVE macro.
  * lnfl/Makefile, lblrtm/Makefile: Added installation code to the link stage
    targets.

  src:TauProd/Infrared/shell_scripts subdirectory.
  * README.instructions: Added rudimentary instructions for TauProd runs.
  * process_TauSpc_files, Remove_Batch_Log_Files, Check_TauSpc_Run_Completion:
    Added svn:executable property.
  * Install_LBLRTM: Cosmetic changes.
  * Check_LBL_Run_Completion: Completed run count is only output if all runs are
    NOT completed. Added svn:executable property.
  * Install_TauProd: Added creation of SRF_Data and TauProfile_data directory and
    SensorInfo file link in the profile set directory during install. Removed
    installation of TauProd on the ${RUN_ROOT_DIR} - unnecessary replication.
  * Start_Processing: Decreased the PROCESS_TAUSPC_INCREMENT and PROCESS_PROFILE_INCREMENT
    macro values for broadband processing from 30,20 to 10,2 respectively.
    Added svn:executable property.
  * process_tape5_files: Added @resources entry in the job command file output.
    Added svn:executable property.



Former-commit-id: f987a1a43be502a8fd23aa0d8bf80100a4683de7

diff --git a/src/TauProd/Infrared/shell_scripts/Install_TauProd b/src/TauProd/Infrared/shell_scripts/Install_TauProd
--- a/src/TauProd/Infrared/shell_scripts/Install_TauProd
+++ b/src/TauProd/Infrared/shell_scripts/Install_TauProd
@@ -30,8 +30,8 @@
 SCRIPT_NAME="`basename $0`"
 
 
-# Root directory definitions
-# --------------------------
+# ABSOLUTE directory definitions
+# ------------------------------
 # The root directory/filesystem where all
 # the software and fixed data is kept
 if [ -z "${ARCHIVE_ROOT_DIR}" ]; then
@@ -44,15 +44,9 @@ if [ -z "${HOME_ROOT_DIR}" ]; then
   HOME_ROOT_DIR="/global/noscrub/${USER}"
 fi
 
-# The root directory/filesystem where the
-# TauProd code will be run
-if [ -z "${RUN_ROOT_DIR}" ]; then
-  RUN_ROOT_DIR="${HOME_ROOT_DIR}/TauProd_scratch"
-fi
 
-
-# Subdirectory names
-# ------------------
+# RELATIVE subdirectory names
+# ---------------------------
 # The transmittance production directory
 TAUPROD_ROOT_DIR="TauProd"
 
@@ -60,7 +54,8 @@ TAUPROD_ROOT_DIR="TauProd"
 SRF_DATA_DIR="SRF_Data"
 DATA_RUNS_DIR="Data_Runs"
 TAPE5_DIR="TAPE5_files"
-SRC_DIR=${CRTM_SOURCE_ROOT}
+TAUPROFILE_DATA_DIR="TauProfile_data"
+SRC_DIR="src/CRTM/trunk"
 IR_TAUPROD_SRC_DIR="${SRC_DIR}/${TAUPROD_ROOT_DIR}/Infrared"
 
 # The SensorInfo filename and directory
@@ -82,7 +77,6 @@ CURRENT_DIR=${PWD}
 # -------------------------------------------
 cd ${HOME}/${IR_TAUPROD_SRC_DIR}
 make
-make install
 cd ${CURRENT_DIR}
 
 
@@ -151,12 +145,14 @@ if [ ! -f ${SENSORINFO_FILE} ]; then
 fi
 
 
-# Copy over TAPE5 data files
-# --------------------------
+# ----------------------------------
+# Set up the profile set directories
+# ----------------------------------
 echo
-echo " Copying TAPE5 data..."
+echo " Setting up the profile set subdirectories..."
 
 # Create the Data_Runs directory if it doesn't exist
+# --------------------------------------------------
 if [ ! -d ${DATA_RUNS_DIR} ]; then
   mkdir ${DATA_RUNS_DIR}
   if [ $? -ne 0 ]; then
@@ -173,10 +169,14 @@ if [ $? -ne 0 ]; then
   exit 2
 fi
 
+
 # Loop over the different profile sets
+# ------------------------------------
 for PROFILE_SET in ${PROFILE_SET_TAGS}; do
 
+
   # Create the profile set directory if it doesn't exist
+  # ----------------------------------------------------
   if [ ! -d ${PROFILE_SET} ]; then
     mkdir ${PROFILE_SET}
     if [ $? -ne 0 ]; then
@@ -192,6 +192,9 @@ for PROFILE_SET in ${PROFILE_SET_TAGS}; do
     exit 2
   fi
 
+
+  # Copy TAPE5 files for this profile set
+  # -------------------------------------
   # Create the TAPE5 files directory if it doesn't exist
   if [ ! -d ${TAPE5_DIR} ]; then
     mkdir ${TAPE5_DIR}
@@ -214,109 +217,40 @@ for PROFILE_SET in ${PROFILE_SET_TAGS}; do
     echo "${SCRIPT_NAME}: Error copying ${PROFILE_SET} TAPE5 files to ${PWD}"
     exit 2
   fi
+  
+  # Return to current profile set directory
+  cd ..
 
-  # Return to Data_Runs directory
-  cd ../..
-
-done
-
-
-# ----------------------------------
-# Install TauProd on ${RUN_ROOT_DIR}
-# ----------------------------------
-
-# Change to the root directory/filesystem on
-# which the TauProd software will be RUN
-# ------------------------------------------
-cd ${RUN_ROOT_DIR}
-if [ $? -ne 0 ]; then
-  echo "${SCRIPT_NAME}: Error changing to ${RUN_ROOT_DIR} root directory from ${PWD}"
-  exit 2
-fi
-
-
-# Create TauProd directory if it doesn't already exist
-# ----------------------------------------------------
-if [ ! -d ${TAUPROD_ROOT_DIR} ]; then
-  mkdir ${TAUPROD_ROOT_DIR}
+  
+  # Link in SensorInfo for this profile set
+  # ---------------------------------------
+  ln -s ${HOME_ROOT_DIR}/${TAUPROD_ROOT_DIR}/SensorInfo .
   if [ $? -ne 0 ]; then
-    echo "${SCRIPT_NAME}: Error creating ${TAUPROD_ROOT_DIR} directory in ${PWD}"
-    exit 2
-  fi
-fi
-
-# Enter TauProd directory for file copying
-cd ${TAUPROD_ROOT_DIR}
-if [ $? -ne 0 ]; then
-  echo "${SCRIPT_NAME}: Error changing to ${TAUPROD_ROOT_DIR} root directory from ${PWD}"
-  exit 2
-fi
-
-
-# Link in the necessary data files from ${HOME_ROOT_DIR}
-# ------------------------------------------------------
-echo
-echo " Linking datafiles from ${HOME_ROOT_DIR}..."
-
-# Create the Data_Runs directory if it doesn't exist
-if [ ! -d ${DATA_RUNS_DIR} ]; then
-  mkdir ${DATA_RUNS_DIR}
-  if [ $? -ne 0 ]; then
-    echo "${SCRIPT_NAME}: Error creating ${DATA_RUNS_DIR} directory in ${PWD}"
-    exit 2
+    echo "${SCRIPT_NAME}: Error linking SensorInfo into ${PROFILE_SET} directory. Continuing..."
   fi
 
-fi
 
-# Enter Data_Runs directory
-cd ${DATA_RUNS_DIR}
-if [ $? -ne 0 ]; then
-  echo "${SCRIPT_NAME}: Error changing to ${DATA_RUNS_DIR} root directory from ${PWD}"
-  exit 2
-fi
-
-# Loop over the different profile sets
-for PROFILE_SET in ${PROFILE_SET_TAGS}; do
-
-  # Create the profile set directory if it doesn't exist
-  if [ ! -d ${PROFILE_SET} ]; then
-    mkdir ${PROFILE_SET}
-    if [ $? -ne 0 ]; then
-      echo "${SCRIPT_NAME}: Error creating ${PROFILE_SET} directory in ${PWD}"
-      exit 2
-    fi
-  fi
-
-  # Enter the profile set directory
-  cd ${PROFILE_SET}
-  if [ $? -ne 0 ]; then
-    echo "${SCRIPT_NAME}: Error changing to ${PROFILE_SET} directory from ${PWD}"
-    exit 2
-  fi
-
-  # Link in the SensorInfo file
-  ln -s ${HOME_ROOT_DIR}/${TAUPROD_ROOT_DIR}/${SENSORINFO_FILE} .
-  if [ $? -ne 0 ]; then
-    echo "${SCRIPT_NAME}: Error linking SensorInfo file in ${PROFILE_SET} directory"
-    exit 2
-  fi
-
-  # Link in the TAPE5 file directory
-  ln -s ${HOME_ROOT_DIR}/${TAUPROD_ROOT_DIR}/${DATA_RUNS_DIR}/${PROFILE_SET}/${TAPE5_DIR} .
-  if [ $? -ne 0 ]; then
-    echo "${SCRIPT_NAME}: Error linking ${TAPE5_DIR} directory in ${PROFILE_SET} directory"
-    exit 2
-  fi
-
-  # Create the SRF data directory if it doesn't exist
+  # Create SRF directory for this profile set
+  # -----------------------------------------
   if [ ! -d ${SRF_DATA_DIR} ]; then
     mkdir ${SRF_DATA_DIR}
     if [ $? -ne 0 ]; then
-      echo "${SCRIPT_NAME}: Error creating ${SRF_DATA_DIR} directory in ${PWD}"
-      exit 2
+      echo "${SCRIPT_NAME}: Error creating ${SRF_DATA_DIR} in ${PROFILE_SET} directory. Continuing..."
     fi
   fi
 
+  
+  # Create final TauProfile directory for this profile set
+  # (This is where the output from the process_TauProfile_files
+  # script goes)
+  # -----------------------------------------------------------
+  if [ ! -d ${TAUPROFILE_DATA_DIR} ]; then
+    mkdir ${TAUPROFILE_DATA_DIR}
+    if [ $? -ne 0 ]; then
+      echo "${SCRIPT_NAME}: Error creating ${TAUPROFILE_DATA_DIR} in ${PROFILE_SET} directory. Continuing..."
+    fi
+  fi
+  
   # Return to Data_Runs directory
   cd ..
 
