src:Utility/InstrumentInfo/SpcCoeff/SpcCoeff_NC2BIN subdirectory.   * run_SpcCoeff_NC2BIN: Added DATA_TYPE to the SpcCoeff_NC2BIN list     os input arguments. Some cosmetic changes.
Former-commit-id: aababb134189fc7dab9b31e0dd9092857664f924

diff --git a/src/Utility/InstrumentInfo/SpcCoeff/SpcCoeff_NC2BIN/run_SpcCoeff_NC2BIN b/src/Utility/InstrumentInfo/SpcCoeff/SpcCoeff_NC2BIN/run_SpcCoeff_NC2BIN
--- a/src/Utility/InstrumentInfo/SpcCoeff/SpcCoeff_NC2BIN/run_SpcCoeff_NC2BIN
+++ b/src/Utility/InstrumentInfo/SpcCoeff/SpcCoeff_NC2BIN/run_SpcCoeff_NC2BIN
@@ -2,10 +2,9 @@
 
 # $Id$
 
-#-------------------------------------------------------------------------------
-#                        -- USAGE DESCRIPTION FUNCTION --
-#-------------------------------------------------------------------------------
-
+# --------------
+# Usage function
+# --------------
 usage()
 {
   echo " Usage: run_SpcCoeff_NC2BIN -l|b[fhs] [-r 4|5|6]"
@@ -14,7 +13,7 @@ usage()
   echo "   directory to Binary format. File with the suffix *.SpcCoeff.nc"
   echo "   are converted into *.SpcCoeff.bin files."
   echo
-  echo "   $Revision$"
+  echo '   $Revision$'
   echo
   echo "     -l       Produce little-endian binary output files"
   echo
@@ -38,187 +37,137 @@ usage()
 }
 
 
-#-------------------------------------------------------------------------------
-#                    -- THE SCRIPT NAME FOR ERROR MESSAGES --
-#-------------------------------------------------------------------------------
+# -----------
+# Main script
+# -----------
 
+# Setup
+# -----
+# Script name for error messages
 SCRIPT_NAME="`basename $0`"
 
+# Defaults
+ENDIAN_TYPE="NONE"
+ENDIAN_RUNTIME_ARG=""
+OVERWRITE="NO"
+FILE_TYPE="SENSOR"
+RELEASE_NUMBER="6"
+DATA_TYPE="1"  # Sensor types only
 
 
-#-------------------------------------------------------------------------------
-#                              -- DEFINE DEFAULTS --
-#-------------------------------------------------------------------------------
+# Parse the command line options
+# ------------------------------
+while getopts :hlbfs:r: OPTVAL; do
 
-  ENDIAN_TYPE="NONE"
-  ENDIAN_RUNTIME_ARG=""
-  OVERWRITE="NO"
-  FILE_TYPE="SENSOR"
-  RELEASE_NUMBER="6"
+  # If option argument looks like
+  # another option exit the loop
+  case ${OPTARG} in
+    -*) break;;
+  esac
 
-
-
-#-------------------------------------------------------------------------------
-#                       -- PARSE THE COMMAND LINE OPTIONS --
-#-------------------------------------------------------------------------------
-
-  while getopts :hlbfs:r: OPTVAL; do
-
-
-    # --------------------------------------------
-    # If option argument looks like another option
-    # exit the loop
-    # --------------------------------------------
-
-    case ${OPTARG} in
-      -*) break;;
-    esac
-
-
-    # ----------------------------
-    # Parse the valid options here
-    # ----------------------------
-
-    case ${OPTVAL} in
-      l)  ENDIAN_TYPE="little";;
-      b)  ENDIAN_TYPE="big";;
-      f)  OVERWRITE="YES";;
-      h)  usage
-          exit 0;;
-      s)  FILE_TYPE="SPECTRAL";;
-      r)  RELEASE_NUMBER=${OPTARG};;
-      :|\?) OPTVAL=${OPTARG}
-            break;;
-    esac
-
-  done
-
-
-  # ----------------------------
-  # Remove the options processed
-  # ----------------------------
-
-  shift `expr ${OPTIND} - 1`
-
-
-  # ------------------------------------------
-  # Now output invalidities based on OPTVAL
-  # Need to do this as getopts does not handle
-  # the situations where an option is passed
-  # as an argument to another option.
-  # ------------------------------------------
-
+  # Parse the valid options here
   case ${OPTVAL} in
-
-
-    # --------------------------------------------
-    # If OPTVAL contains nothing, then all options
-    # have been successfully parsed
-    # --------------------------------------------
-
-    \?) if [ $# -ne 0 ]; then
-          ( echo "${SCRIPT_NAME}: Invalid argument(s) $*" ; echo ; usage ) | more
-          exit 2
-        fi;;
-
-
-    # ------------------------------------
-    # Valid options, but missing arguments
-    # ------------------------------------
-
-    r) ( echo "${SCRIPT_NAME}: '-${OPTVAL}' option requires an argument" ; usage ) | more
-       exit 2;;
-
-
-    # --------------
-    # Invalid option
-    # --------------
-
-    ?) ( echo "${SCRIPT_NAME}: Invalid option '-${OPTARG}'" ; usage ) | more
-       exit 2;;
-
+    l)  ENDIAN_TYPE="little";;
+    b)  ENDIAN_TYPE="big";;
+    f)  OVERWRITE="YES";;
+    h)  usage
+        exit 0;;
+    s)  FILE_TYPE="SPECTRAL"
+        DATA_TYPE="2";;
+    r)  RELEASE_NUMBER=${OPTARG};;
+    :|\?) OPTVAL=${OPTARG}
+          break;;
   esac
+done
 
 
-  # ---------------------------------------
-  # Check that an endian type was specified
-  # ---------------------------------------
+# Remove the options processed
+# ----------------------------
+shift `expr ${OPTIND} - 1`
 
-  if [ ${ENDIAN_TYPE} = "NONE" ]; then
-    ( echo "${SCRIPT_NAME}: Must specify and endian type, -l or -b" ; echo ; usage ) | more
-    exit 2
+
+# Now output invalidities based on OPTVAL
+# Need to do this as getopts does not handle
+# the situations where an option is passed
+# as an argument to another option.
+# ------------------------------------------
+case ${OPTVAL} in
+
+  # If OPTVAL contains nothing, then all options
+  # have been successfully parsed
+  \?) if [ $# -ne 0 ]; then
+        ( echo "${SCRIPT_NAME}: Invalid argument(s) $*" ; echo ; usage ) | more
+        exit 2
+      fi;;
+
+  # Valid options, but missing arguments
+  r) ( echo "${SCRIPT_NAME}: '-${OPTVAL}' option requires an argument" ; usage ) | more
+     exit 2;;
+
+  # Invalid option
+  ?) ( echo "${SCRIPT_NAME}: Invalid option '-${OPTARG}'" ; usage ) | more
+     exit 2;;
+
+esac
+
+
+# Check that an endian type was specified
+# ------------------------------------------
+if [ ${ENDIAN_TYPE} = "NONE" ]; then
+  ( echo "${SCRIPT_NAME}: Must specify and endian type, -l or -b" ; echo ; usage ) | more
+  exit 2
+fi
+
+
+# Check that a valid Release number was specified
+# -----------------------------------------------
+case ${RELEASE_NUMBER} in
+  4|5|6) ;;
+  *) ( echo "${SCRIPT_NAME}: Invalid Release number specified" ; echo ; usage ) | more
+     exit 2;;
+esac
+
+
+# Check that a valid Release number and file type combo was specified
+# -------------------------------------------------------------------
+MIN_SPECTRAL_RELEASE=6
+if [ ${RELEASE_NUMBER} -lt ${MIN_SPECTRAL_RELEASE} -a "${FILE_TYPE}" = "SPECTRAL" ]; then
+  ( echo "${SCRIPT_NAME}: Spectral file type only valid for Release ${MIN_SPECTRAL_RELEASE} and higher" ; echo ; usage ) | more
+  exit 2
+fi
+
+
+# Assign processing parameters
+# ----------------------------
+# Lahey Linux compiler-specific run time option
+if [ ${ENDIAN_TYPE} = "big" ]; then
+  ENDIAN_RUNTIME_ARG="-Wl,-T"
+fi
+EXE_FILE="SpcCoeff_NC2BIN.R${RELEASE_NUMBER}"
+LOG_FILE="${EXE_FILE}.log"
+
+
+# Loop over netCDF SpcCoeff files
+# -------------------------------
+for NC_FILE in `ls *.SpcCoeff.nc`; do
+
+  # Create binary filename
+  BIN_FILE="`basename ${NC_FILE} .nc`.bin"
+
+  # Check to see if the output file exists
+  if [ -f ${BIN_FILE} -a ${OVERWRITE} = "NO" ]; then
+    echo " Output file ${BIN_FILE} already exists. Skipping to next file..."
+    continue
   fi
 
-
-  # -----------------------------------------------
-  # Check that a valid Release number was specified
-  # -----------------------------------------------
-
-  case ${RELEASE_NUMBER} in
-    4|5|6) ;;
-    *) ( echo "${SCRIPT_NAME}: Invalid Release number specified" ; echo ; usage ) | more
-       exit 2;;
-  esac
-
-  # -------------------------------------------------------------------
-  # Check that a valid Release number and file type combo was specified
-  # -------------------------------------------------------------------
-
-  MIN_SPECTRAL_RELEASE=6
-  if [ ${RELEASE_NUMBER} -lt ${MIN_SPECTRAL_RELEASE} -a "${FILE_TYPE}" = "SPECTRAL" ]; then
-    ( echo "${SCRIPT_NAME}: Spectral file type only valid for Release ${MIN_SPECTRAL_RELEASE} and higher" ; echo ; usage ) | more
-    exit 2
-  fi
-
-
-#------------------------------------------------------------------------------#
-#                       -- ASSIGN PROCESSING PARAMETERS --                     #
-#------------------------------------------------------------------------------#
-
-  # -- Lahey Linux compiler-specific run time option
-  if [ ${ENDIAN_TYPE} = "big" ]; then
-    ENDIAN_RUNTIME_ARG="-Wl,-T"
-  fi
-
-  EXE_FILE="SpcCoeff_NC2BIN.R${RELEASE_NUMBER}"
-  LOG_FILE="${EXE_FILE}.log"
-
-
-
-#------------------------------------------------------------------------------#
-#                  -- BEGIN LOOP OVER netCDF SpcCoeff FILES --                 #
-#------------------------------------------------------------------------------#
-
-  for NC_FILE in `ls *.SpcCoeff.nc`; do
-
-
-    # ----------------------
-    # Create binary filename
-    # ----------------------
-
-    BIN_FILE="`basename ${NC_FILE} .nc`.bin"
-
-
-    # --------------------------------------
-    # Check to see if the output file exists
-    # --------------------------------------
-
-    if [ -f ${BIN_FILE} -a ${OVERWRITE} = "NO" ]; then
-      echo " Output file ${BIN_FILE} already exists. Skipping to next file..."
-      continue
-    fi
-
-
-    # ----------------
-    # Convert the file
-    # ----------------
-
-    echo " Converting Release ${RELEASE_NUMBER} ${NC_FILE} to ${ENDIAN_TYPE} endian binary format file ${BIN_FILE}..."
-    ${EXE_FILE} ${ENDIAN_RUNTIME_ARG} <<-NoMoreInput >> ${LOG_FILE}
+  # Convert the file
+  echo " Converting Release ${RELEASE_NUMBER} ${NC_FILE} to ${ENDIAN_TYPE} endian binary format file ${BIN_FILE}..."
+  ${EXE_FILE} ${ENDIAN_RUNTIME_ARG} <<-NoMoreInput >> ${LOG_FILE}
+	${DATA_TYPE}
 	${NC_FILE}
 	${BIN_FILE}
 	${FILE_TYPE}
 	NoMoreInput
-  done
+done
 
 exit
